monitor=HDMI-A-1,1920x1080@60.0,0x0,1.0
monitor=DP-2,2560x1440@74.97,1920x0,1.25
monitor=DP-3,1920x1080@60.0,3968x0,1.0

# Else
# Monitors
monitor=,preferred,auto,1

# High Refresh Rate
monitor=,highrr,auto,1

# High Resolution
monitor=,highres,auto,1
